 
CREATE TABLE WORKITEM(
	WORKITEM_ID	 VARCHAR(128),	
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(200),
	STATUS VARCHAR(30),
	WORKITEM_PAYLOAD BLOB,
	CREATED_BY VARCHAR(30),
	CREATED_DATE DATETIME,
	UPDATED_BY VARCHAR(30),
	UPDATED_DATE DATETIME,
	VERSION INT,
   PRIMARY KEY (WORKITEM_ID)
);

CREATE TABLE WORKITEM_AUDIT(
	WORKITEM_AUDIT_ID	 VARCHAR(128),	
	WORKITEM_ID VARCHAR(128),
	COMMENTS VARCHAR(200),
	CREATED_BY VARCHAR(30),
	CREATED_DATE DATETIME,
   PRIMARY KEY (WORKITEM_AUDIT_ID)
);

