server:
  port: 1111

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:1111
    registerWithEureka: false
    fetchRegistry: false
    
    
